# Generated by Django 2.0.2 on 2019-04-07 04:12

from django.db import migrations, models
import django.db.models.deletion
import wagtail.search.index


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogpage_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_first_name', models.CharField(max_length=30)),
                ('author_last_name', models.CharField(max_length=30)),
                ('author_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('genre', models.CharField(choices=[('R', 'Rock'), ('J/B', 'Jazz/Blues'), ('B', 'Blues'), ('J', 'Jazz'), ('P', 'Pop'), ('H', 'Hip-Hop')], max_length=255)),
                ('published_date', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Author')),
            ],
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
